name: Deploy Prefect flow
on:
  push:
    branches:
      - main

jobs:
  deploy_flow:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
        
      - name: Run Prefect Deploy
        shell: bash
        env:
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          REDIS_CLIENT_HOST: ${{ secrets.REDIS_CLIENT_HOST }}
          REDIS_CLIENT_PORT: ${{ secrets.REDIS_CLIENT_PORT }}
          REDIS_CLIENT_PASSWORD: ${{ secrets.REDIS_CLIENT_PASSWORD }}
          REDIS_STREAM_NAME: ${{ secrets.REDIS_STREAM_NAME }}
        run: |
          pip install -r requirements.txt
          prefect deploy --all